#!/bin/bash

# Abort on Error
set -euo pipefail

# Determine toolpath if not set already
relativepath="../" # Define relative path to go from this script to the root level of the tool
if [[ ! -v toolpath ]]; then scriptpath=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ); toolpath=$(realpath --canonicalize-missing ${scriptpath}/${relativepath}); fi

# Load Configuration
source "${toolpath}/config.sh"

# Load Functions
source "${toolpath}/functions.sh"

# Set error trap AFTER sourcing
trap 'error_handler $? $LINENO "$BASH_SOURCE"' ERR

# ============================================
# Install Container Configuration Files
# ============================================
# Installs 6 config files under INSTALL_PREFIX (isolated tree), NOT /etc:
#   1. containers.conf  -> ${INSTALL_PREFIX}/etc/containers/containers.conf
#   2. seccomp.json     -> ${INSTALL_PREFIX}/share/containers/seccomp.json
#   3. policy.json      -> ${INSTALL_PREFIX}/etc/containers/policy.json
#   4. default.yaml     -> ${INSTALL_PREFIX}/etc/containers/registries.d/default.yaml
#   5. storage.conf     -> ${INSTALL_PREFIX}/etc/containers/storage.conf
#   6. registries.conf  -> ${INSTALL_PREFIX}/etc/containers/registries.conf

# INSTALL_PREFIX=/usr => conventional system layout (upstream-compatible):
# configs in /etc/containers, seccomp in /usr/share/containers, no path rewriting.
# Any other prefix => self-contained isolated tree under that prefix.
if [[ "${INSTALL_PREFIX}" == "/usr" ]]; then
    CFG_ROOT="/etc/containers"
    SHARE_ROOT="/usr/share/containers"
    ISOLATED=0
else
    CFG_ROOT="${INSTALL_PREFIX}/etc/containers"
    SHARE_ROOT="${INSTALL_PREFIX}/share/containers"
    ISOLATED=1
fi

step_start "Creating configuration directories"
mkdir -p "${DESTDIR:-}${CFG_ROOT}"
mkdir -p "${DESTDIR:-}${CFG_ROOT}/registries.d"
mkdir -p "${DESTDIR:-}${SHARE_ROOT}"
step_done

step_start "Installing configuration files"

# 1. containers.conf (from project config/ directory)
# In isolated mode, substitute the __PREFIX__ token so the file is fully
# self-contained. In system mode (/usr) the stock template is already correct.
echo "  Installing containers.conf -> ${DESTDIR:-}${CFG_ROOT}/containers.conf"
if [[ "${ISOLATED}" == "1" ]]; then
    sed "s|__PREFIX__|${INSTALL_PREFIX}|g" "${toolpath}/config/containers.conf" \
        > "${DESTDIR:-}${CFG_ROOT}/containers.conf"
else
    install -m 0644 "${toolpath}/config/containers.conf" "${DESTDIR:-}${CFG_ROOT}/containers.conf"
fi

# 2. seccomp.json (generated by Phase 11 container-libs build via common/cmd/seccomp/generate.go)
SECCOMP_SRC="${BUILD_ROOT}/container-libs/common/pkg/seccomp/seccomp.json"
if [ ! -f "${SECCOMP_SRC}" ]; then
    echo "ERROR: seccomp.json not found at ${SECCOMP_SRC}" >&2
    echo "  Ensure build_container-libs.sh ran successfully first" >&2
    exit 1
fi
echo "  Installing seccomp.json -> ${DESTDIR:-}${SHARE_ROOT}/seccomp.json"
install -m 0644 "${SECCOMP_SRC}" "${DESTDIR:-}${SHARE_ROOT}/seccomp.json"

# 3. policy.json
echo "  Installing policy.json -> ${DESTDIR:-}${CFG_ROOT}/policy.json"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default-policy.json" "${DESTDIR:-}${CFG_ROOT}/policy.json"

# 4. default.yaml
echo "  Installing default.yaml -> ${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default.yaml" "${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml"

# 5. storage.conf
# Install upstream template. In isolated mode, generate separate rootless
# (storage.conf) and rootful (storage-root.conf) configurations with isolated
# runroots to prevent aardvark-dns / netavark crossover collisions.
echo "  Installing storage.conf -> ${DESTDIR:-}${CFG_ROOT}/storage.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/storage/storage.conf" "${DESTDIR:-}${CFG_ROOT}/storage.conf"
if [[ "${ISOLATED}" == "1" ]]; then
    # In storage.conf (used for rootless): inject runroot directly under [storage]
    # Do NOT inject graphroot here so rootless defaults cleanly to XDG_DATA_HOME.
    sed -i '/^\[storage\]/a runroot = "/run/user/$UID/podman-upstream/storage"' "${DESTDIR:-}${CFG_ROOT}/storage.conf"

    # In storage-root.conf (used for rootful/sudo): pin both graphroot and runroot
    cp "${DESTDIR:-}${CFG_ROOT}/storage.conf" "${DESTDIR:-}${CFG_ROOT}/storage-root.conf"
    sed -i 's|runroot = "/run/user/\$UID/podman-upstream/storage"|runroot = "/run/podman-upstream/storage"|' "${DESTDIR:-}${CFG_ROOT}/storage-root.conf"
    sed -i "/^\[storage\]/a graphroot = \"${INSTALL_PREFIX}/var/lib/containers/storage\"" "${DESTDIR:-}${CFG_ROOT}/storage-root.conf"
fi

# 6. registries.conf
# Install upstream template. In isolated mode, ensure an explicit
# unqualified-search list so short-name pulls resolve identically rootless and
# rootful (don't rely on Podman's undocumented short-name default).
echo "  Installing registries.conf -> ${DESTDIR:-}${CFG_ROOT}/registries.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/image/registries.conf" "${DESTDIR:-}${CFG_ROOT}/registries.conf"
if [[ "${ISOLATED}" == "1" ]] && ! grep -q '^unqualified-search-registries' "${DESTDIR:-}${CFG_ROOT}/registries.conf"; then
    printf '\nunqualified-search-registries = ["docker.io"]\n' >> "${DESTDIR:-}${CFG_ROOT}/registries.conf"
fi

# 7. podman-upstream wrapper (isolated mode ONLY).
# The isolated tree is non-functional as a default invocation without it
# (raw podman leaks to /usr). Install it next to the prefix binaries so it is
# the natural entrypoint. Skipped entirely in system mode (/usr) to keep that
# install bit-for-bit upstream-compatible.
if [[ "${ISOLATED}" == "1" ]]; then
    echo "  Installing podman-upstream -> ${DESTDIR:-}${INSTALL_PREFIX}/bin/podman-upstream"
    install -m 0755 "${toolpath}/podman-upstream.sh" "${DESTDIR:-}${INSTALL_PREFIX}/bin/podman-upstream"
fi

# 8. Isolated systemd unit files (isolated mode ONLY).
# Stock podman unit files hardcode /usr paths and the %t/podman/podman.sock socket,
# which collides with Ubuntu host podman daemon. We generate isolated units.
if [[ "${ISOLATED}" == "1" ]]; then
    echo "  Configuring isolated systemd units..."
    mkdir -p "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/user"
    mkdir -p "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/system"

    # User socket & service
    cat << EOF > "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/user/podman-upstream.socket"
[Unit]
Description=Isolated Upstream Podman API Socket
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=%t/podman-upstream/podman.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
EOF

    cat << EOF > "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/user/podman-upstream.service"
[Unit]
Description=Isolated Upstream Podman API Service
Requires=podman-upstream.socket
After=podman-upstream.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Delegate=true
Type=exec
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=${INSTALL_PREFIX}/bin/podman-upstream \$LOGGING system service

[Install]
WantedBy=default.target
EOF

    # System socket & service
    cat << EOF > "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/system/podman-upstream.socket"
[Unit]
Description=Isolated Upstream Podman API Socket (System)
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=/run/podman-upstream/podman.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
EOF

    cat << EOF > "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/system/podman-upstream.service"
[Unit]
Description=Isolated Upstream Podman API Service (System)
Requires=podman-upstream.socket
After=podman-upstream.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Delegate=true
Type=exec
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=${INSTALL_PREFIX}/bin/podman-upstream \$LOGGING system service

[Install]
WantedBy=default.target
EOF

    # Remove colliding un-isolated units that make install might have staged
    rm -f "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/user/podman.socket" \
          "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/user/podman.service" \
          "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/system/podman.socket" \
          "${DESTDIR:-}${INSTALL_PREFIX}/lib/systemd/system/podman.service"
fi

step_done

step_start "Verifying installed configuration files"
VERIFY_OK=true

for dest in \
    "${DESTDIR:-}${CFG_ROOT}/containers.conf" \
    "${DESTDIR:-}${SHARE_ROOT}/seccomp.json" \
    "${DESTDIR:-}${CFG_ROOT}/policy.json" \
    "${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml" \
    "${DESTDIR:-}${CFG_ROOT}/storage.conf" \
    "${DESTDIR:-}${CFG_ROOT}/registries.conf"; do
    if test -f "${dest}"; then
        echo "  OK: ${dest}"
    else
        echo "  MISSING: ${dest}" >&2
        VERIFY_OK=false
    fi
done

if [ "${VERIFY_OK}" = false ]; then
    echo "ERROR: One or more configuration files failed to install" >&2
    exit 1
fi

echo "  All 6 configuration files installed successfully"
step_done
