#!/bin/bash

# Abort on Error
set -euo pipefail

# Determine toolpath if not set already
relativepath="../" # Define relative path to go from this script to the root level of the tool
if [[ ! -v toolpath ]]; then scriptpath=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ); toolpath=$(realpath --canonicalize-missing ${scriptpath}/${relativepath}); fi

# Load Configuration
source "${toolpath}/config.sh"

# Load Functions
source "${toolpath}/functions.sh"

# Set error trap AFTER sourcing
trap 'error_handler $? $LINENO "$BASH_SOURCE"' ERR

# ============================================
# Install Container Configuration Files
# ============================================
# Installs 6 config files under INSTALL_PREFIX (isolated tree), NOT /etc:
#   1. containers.conf  -> ${INSTALL_PREFIX}/etc/containers/containers.conf
#   2. seccomp.json     -> ${INSTALL_PREFIX}/share/containers/seccomp.json
#   3. policy.json      -> ${INSTALL_PREFIX}/etc/containers/policy.json
#   4. default.yaml     -> ${INSTALL_PREFIX}/etc/containers/registries.d/default.yaml
#   5. storage.conf     -> ${INSTALL_PREFIX}/etc/containers/storage.conf
#   6. registries.conf  -> ${INSTALL_PREFIX}/etc/containers/registries.conf

CFG_ROOT="${INSTALL_PREFIX}/etc/containers"
SHARE_ROOT="${INSTALL_PREFIX}/share/containers"

step_start "Creating configuration directories"
mkdir -p "${DESTDIR:-}${CFG_ROOT}"
mkdir -p "${DESTDIR:-}${CFG_ROOT}/registries.d"
mkdir -p "${DESTDIR:-}${SHARE_ROOT}"
step_done

step_start "Installing configuration files"

# 1. containers.conf (from project config/ directory)
echo "  Installing containers.conf -> ${DESTDIR:-}${CFG_ROOT}/containers.conf"
install -m 0644 "${toolpath}/config/containers.conf" "${DESTDIR:-}${CFG_ROOT}/containers.conf"

# 2. seccomp.json (generated by Phase 11 container-libs build via common/cmd/seccomp/generate.go)
SECCOMP_SRC="${BUILD_ROOT}/container-libs/common/pkg/seccomp/seccomp.json"
if [ ! -f "${SECCOMP_SRC}" ]; then
    echo "ERROR: seccomp.json not found at ${SECCOMP_SRC}" >&2
    echo "  Ensure build_container-libs.sh ran successfully first" >&2
    exit 1
fi
echo "  Installing seccomp.json -> ${DESTDIR:-}${SHARE_ROOT}/seccomp.json"
install -m 0644 "${SECCOMP_SRC}" "${DESTDIR:-}${SHARE_ROOT}/seccomp.json"

# 3. policy.json
echo "  Installing policy.json -> ${DESTDIR:-}${CFG_ROOT}/policy.json"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default-policy.json" "${DESTDIR:-}${CFG_ROOT}/policy.json"

# 4. default.yaml
echo "  Installing default.yaml -> ${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml"
install -m 0644 "${BUILD_ROOT}/container-libs/image/default.yaml" "${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml"

# 5. storage.conf
echo "  Installing storage.conf -> ${DESTDIR:-}${CFG_ROOT}/storage.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/storage/storage.conf" "${DESTDIR:-}${CFG_ROOT}/storage.conf"

# 6. registries.conf
echo "  Installing registries.conf -> ${DESTDIR:-}${CFG_ROOT}/registries.conf"
install -m 0644 "${BUILD_ROOT}/container-libs/image/registries.conf" "${DESTDIR:-}${CFG_ROOT}/registries.conf"

step_done

step_start "Verifying installed configuration files"
VERIFY_OK=true

for dest in \
    "${DESTDIR:-}${CFG_ROOT}/containers.conf" \
    "${DESTDIR:-}${SHARE_ROOT}/seccomp.json" \
    "${DESTDIR:-}${CFG_ROOT}/policy.json" \
    "${DESTDIR:-}${CFG_ROOT}/registries.d/default.yaml" \
    "${DESTDIR:-}${CFG_ROOT}/storage.conf" \
    "${DESTDIR:-}${CFG_ROOT}/registries.conf"; do
    if test -f "${dest}"; then
        echo "  OK: ${dest}"
    else
        echo "  MISSING: ${dest}" >&2
        VERIFY_OK=false
    fi
done

if [ "${VERIFY_OK}" = false ]; then
    echo "ERROR: One or more configuration files failed to install" >&2
    exit 1
fi

echo "  All 6 configuration files installed successfully"
step_done
